# fly.toml app configuration file generated for demol-snowy-fire-686 on 2025-03-21T16:38:20+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demol-snowy-fire-686'
primary_region = 'ams'

[build]

[env]
  OAUTH2_BASEURL = "https://optis.auth.eu-west-1.amazoncognito.com"
  OAUTH2_AUTHORIZATIONURL = "https://optis.auth.eu-west-1.amazoncognito.com/oauth2/authorize"
  OAUTH2_TOKENURL = "https://optis.auth.eu-west-1.amazoncognito.com/oauth2/token"
  OAUTH2_USERINFOURL = "https://optis.auth.eu-west-1.amazoncognito.com/oauth2/userInfo"
  OAUTH2_CLIENTID = "6cdhg4buar22jvs0gsjkspa741"
  OAUTH2_CALLBACKURL = "https://demol-snowy-fire-686.fly.dev/auth/callback"
  OAUTH2_LOGOUTURL = "https://demol-snowy-fire-686.fly.dev/logout"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
