# fly.toml app configuration file generated for demol-3203 on 2023-05-03T11:48:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "demol-3203"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[env]
  OAUTH2_AUTHORIZATIONURL = "https://optis.auth.eu-west-1.amazoncognito.com/oauth2/authorize"
  OAUTH2_BASEURL = "https://optis.auth.eu-west-1.amazoncognito.com"
  OAUTH2_CALLBACKURL = "https://demol-3203.fly.dev/auth/callback"
  OAUTH2_CLIENTID = "6cdhg4buar22jvs0gsjkspa741"
  OAUTH2_LOGOUTURL = "https://demol-3203.fly.dev/logout"
  OAUTH2_TOKENURL = "https://optis.auth.eu-west-1.amazoncognito.com/oauth2/token"
  OAUTH2_USERINFOURL = "https://optis.auth.eu-west-1.amazoncognito.com/oauth2/userInfo"

[[mounts]]
  source = "data_machines"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"
